# -*- coding: utf-8 -*-
"""GMC_first_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182HCncCiv51eIryCbiO7O-MzwgGUdAAn
"""



"""# Welcome to the world of Python!
## Intoducing the print function
`print` is a bulit in function in python

"""

print ("Hello World")

print("My name is Damilola")

print("I'm learning about gitbub and I'm going to add my work to a repository I cloned")